<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEuXH7o3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEuXH7o3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEuXH7o3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEuXH7o3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEuXH7o3\App_KernelDevDebugContainer([
    'container.build_hash' => 'EuXH7o3',
    'container.build_id' => 'b8452e0d',
    'container.build_time' => 1660643489,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEuXH7o3');
