<?php

namespace ContainerEuXH7o3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_65xPtEiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.65xPtEi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.65xPtEi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PokemonController::compare' => ['privates', '.service_locator.FZOpMlq', 'get_ServiceLocator_FZOpMlqService', true],
            'App\\Controller\\PokemonController::filterByType' => ['privates', '.service_locator.FZOpMlq', 'get_ServiceLocator_FZOpMlqService', true],
            'App\\Controller\\PokemonController::index' => ['privates', '.service_locator.KfjGDYf', 'get_ServiceLocator_KfjGDYfService', true],
            'App\\Controller\\PokemonController::show' => ['privates', '.service_locator.YorEgXw', 'get_ServiceLocator_YorEgXwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\PokemonController:compare' => ['privates', '.service_locator.FZOpMlq', 'get_ServiceLocator_FZOpMlqService', true],
            'App\\Controller\\PokemonController:filterByType' => ['privates', '.service_locator.FZOpMlq', 'get_ServiceLocator_FZOpMlqService', true],
            'App\\Controller\\PokemonController:index' => ['privates', '.service_locator.KfjGDYf', 'get_ServiceLocator_KfjGDYfService', true],
            'App\\Controller\\PokemonController:show' => ['privates', '.service_locator.YorEgXw', 'get_ServiceLocator_YorEgXwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\PokemonController::compare' => '?',
            'App\\Controller\\PokemonController::filterByType' => '?',
            'App\\Controller\\PokemonController::index' => '?',
            'App\\Controller\\PokemonController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PokemonController:compare' => '?',
            'App\\Controller\\PokemonController:filterByType' => '?',
            'App\\Controller\\PokemonController:index' => '?',
            'App\\Controller\\PokemonController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
