<?php

namespace ContainerEuXH7o3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KfjGDYfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KfjGDYf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KfjGDYf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pokemonRepository' => ['privates', 'App\\Repository\\PokemonRepository', 'getPokemonRepositoryService', true],
            'typeRepository' => ['privates', 'App\\Repository\\TypeRepository', 'getTypeRepositoryService', true],
        ], [
            'pokemonRepository' => 'App\\Repository\\PokemonRepository',
            'typeRepository' => 'App\\Repository\\TypeRepository',
        ]);
    }
}
